SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WEB_ACCESS](
	[ID] [numeric](18, 0) IDENTITY(1,1) NOT NULL,
	[IP4] [nchar](15) NOT NULL,
	[IP6] [nchar](39) NULL,
	[COUNTRY] [nvarchar](50) NULL,
	[COUNTRY_CODE] [nchar](3) NULL,
	[CITY] [nvarchar](50) NULL,
	[CONTINENT] [nvarchar](50) NULL,
	[LATITUDE] [numeric](9, 6) NULL,
	[LONGITUDE] [numeric](9, 6) NULL,
	[TIMEZONE] [nvarchar](50) NULL,
	[POSTAL_CODE] [nvarchar](10) NULL,
	[ISP_NAME] [nvarchar](50) NULL,
	[USER_AGENT] [nvarchar](512) NULL,
	[VISIT_DATETIME] [datetime] NOT NULL,
	[VISIT_URL] [nvarchar](512) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WEB_ACCESS] ADD  CONSTRAINT [PK_WEB_ACCESS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[WEB_ACCESS] ADD  DEFAULT (getdate()) FOR [VISIT_DATETIME]
GO